In [11]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [ ]:
#Q1

In [12]:
data=pd.read_csv("Cutlets.csv")

In [13]:
unit1=pd.Series(data.iloc[:,0])
unit2=pd.Series(data.iloc[:,1])

p_value=stats.ttest_ind(unit1,unit2)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47223947245995)

In [14]:
p_value[1]

0.47223947245995

In [ ]:
# here we accept null hypothesis since p_value>alpha

In [ ]:
#Q2

In [18]:
data1=pd.read_csv("LabTAT.csv")

In [19]:
p_value=stats.f_oneway(data1.iloc[:,0],data1.iloc[:,1],data1.iloc[:,2],data1.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
#p value equals 2.11*10^-57  which is less than alpha 0.05 Reject Null Hypothesis


In [ ]:
#Q3

In [20]:
data2=pd.read_csv("BuyerRatio.csv")

In [21]:
males=pd.Series(data2.iloc[0,1:]).values
males

array([50, 142, 131, 70], dtype=object)

In [22]:
females=pd.Series(data2.iloc[1,1:]).values
females

array([435, 1523, 1356, 750], dtype=object)

In [23]:
z=[males,females]
z

[array([50, 142, 131, 70], dtype=object),
 array([435, 1523, 1356, 750], dtype=object)]

In [25]:
from scipy.stats import chi2_contingency
males=chi2_contingency(z)
males[1]

0.6603094907091882

In [ ]:
#p value is greater than Alpha value 0.05 hence we will Accept H0


In [ ]:
#Q4

In [27]:
data3=pd.read_csv("Costomer+OrderForm.csv")
data3.Phillippines.value_counts()


Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [28]:
data3.Indonesia.value_counts()


Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [29]:
data3.Malta.value_counts()


Error Free    269
Defective      31
Name: Malta, dtype: int64

In [30]:
data3.India.value_counts()


Error Free    280
Defective      20
Name: India, dtype: int64

In [32]:
array = [[271,267,269,280],[29,33,31,20]]
array

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [34]:
x=chi2_contingency(array)
x[1]

0.2771020991233135

In [ ]:
#p>alpha ==> accept H0